### ISSUE TITLE
[Bug] - BetterRoleColors - Discrod crashes when used along with other plugins on large servers.

### ISSUE THREAD

**Issue by Igor050301** [zerebos/BetterDiscordAddons#718]
**Which plugin/theme is this about?**
BetterRoleColor

**Describe the Bug**
Discrod crashes when used along with other plugins on large servers. This usually happens within 1-3 minutes of being on the server and switching between different channels. Crashes only happen when BetterRoleColors is enabled.
List of other enabled plugins:
1. BDFDB
2. CallTimeCounter
3. CharCounter
4. GameActivityToggle
5. ImageUtilities
6. InvisibleTyping
7. PinIcon
8. PluginRepo
9. QuickView
10. RoleMembers
11. RoleMentionIcons
12. SplitLargeMessages
13. TypingIndicator
14. TypingUsersAvatars

**To Reproduce**
Possibly download and activate these plugins along with BetterRoleColors
**Expected Behavior**
No crashes
**Screenshots**
N/A
**Discord Version**
Stable
**Additional Context**
N/A

**Comment by rauenzi** [comment]
I won't be downloading all of those. You can provide the console errors if you like from the crash.

**Comment by Igor050301** [comment]
Here are errors from the debug.log relating to  BetterRoleColors before first crash:
```
[2023-04-21 06:07:58.573][CONSOLE:ERROR] [PluginManager] Unable to fire observer for BetterRoleColors v0.10.1
 Cannot read properties of null (reading 'style')
TypeError: Cannot read properties of null (reading 'style')
    at BetterRoleColors.colorNameTags (betterdiscord://plugins/BetterRoleColors.plugin.js:419:30)
    at BetterRoleColors.observer (betterdiscord://plugins/BetterRoleColors.plugin.js:375:18)
    at A.onMutation (betterdiscord/renderer.js:4:37198)
    at MutationObserver.<anonymous> (betterdiscord/renderer.js:4:31948)
[2023-04-21 06:08:01.994][CONSOLE:ERROR] Cannot read properties of null (reading 'getModeId')
TypeError: Cannot read properties of null (reading 'getModeId')
    at https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.20.0/min/vs/language/css/cssMode.js:7:734148
```    
After reload:
```
[2023-04-21 06:41:02.080][CONSOLE:ERROR] [PluginManager] Unable to fire observer for BetterRoleColors v0.10.1
 element.querySelectorAll is not a function
TypeError: element.querySelectorAll is not a function
    at BetterRoleColors.colorMentions (betterdiscord://plugins/BetterRoleColors.plugin.js:453:31)
    at BetterRoleColors.observer (betterdiscord://plugins/BetterRoleColors.plugin.js:374:18)
    at A.onMutation (betterdiscord/renderer.js:4:37198)
    at MutationObserver.<anonymous> (betterdiscord/renderer.js:4:31948)
[2023-04-21 06:41:02.080][CONSOLE:ERROR] [PluginManager] Unable to fire observer for BetterRoleColors v0.10.1

 element.querySelectorAll is not a function
TypeError: element.querySelectorAll is not a function
    at BetterRoleColors.colorMentions (betterdiscord://plugins/BetterRoleColors.plugin.js:453:31)
    at BetterRoleColors.observer (betterdiscord://plugins/BetterRoleColors.plugin.js:374:18)
    at A.onMutation (betterdiscord/renderer.js:4:37198)
    at MutationObserver.<anonymous> (betterdiscord/renderer.js:4:31948)
[2023-04-21 06:41:02.080][CONSOLE:ERROR] [PluginManager] Unable to fire observer for BetterRoleColors v0.10.1

 element.querySelectorAll is not a function
TypeError: element.querySelectorAll is not a function
    at BetterRoleColors.colorMentions (betterdiscord://plugins/BetterRoleColors.plugin.js:453:31)
    at BetterRoleColors.observer (betterdiscord://plugins/BetterRoleColors.plugin.js:374:18)
    at A.onMutation (betterdiscord/renderer.js:4:37198)
    at MutationObserver.<anonymous> (betterdiscord/renderer.js:4:31948)
[2023-04-21 06:41:02.990][CONSOLE:ERROR] Menu API only allows Items and groups of Items as children. Received function ef(e){return null} (object) instead
Error: Menu API only allows Items and groups of Items as children. Received function ef(e){return null} (object) instead
    at https://discord.com/assets/5d60241f1a35b792bb74.js:2934:199
    at Array.reduce (<anonymous>)
    at So (https://discord.com/assets/5d60241f1a35b792bb74.js:2933:14)
    at No (https://discord.com/assets/5d60241f1a35b792bb74.js:2936:940)
    at eval (betterdiscord://plugins/0BDFDB.plugin.js:2901:21)
    at Sa (https://discord.com/assets/5d60241f1a35b792bb74.js:1779:54)
    at gu (https://discord.com/assets/5d60241f1a35b792bb74.js:1833:146)
    at Ic (https://discord.com/assets/5d60241f1a35b792bb74.js:1826:89)
    at mc (https://discord.com/assets/5d60241f1a35b792bb74.js:1826:17)
    at hc (https://discord.com/assets/5d60241f1a35b792bb74.js:1825:867)
    at uc (https://discord.com/assets/5d60241f1a35b792bb74.js:1822:983)
    at Fi (https://discord.com/assets/5d60241f1a35b792bb74.js:1762:577)
    at lc (https://discord.com/assets/5d60241f1a35b792bb74.js:1823:498)
    at https://discord.com/assets/5d60241f1a35b792bb74.js:1842:522
    at el (https://discord.com/assets/5d60241f1a35b792bb74.js:1842:561)
    at t.render (https://discord.com/assets/5d60241f1a35b792bb74.js:1846:205)
    at MyReact.render (betterdiscord://plugins/0BDFDB.plugin.js:2885:40)
    at MyReact.hookCall (betterdiscord://plugins/0BDFDB.plugin.js:2900:23)
    at loadLibrary (betterdiscord://plugins/0BDFDB.plugin.js:7883:60)
    at parseData (betterdiscord://plugins/0BDFDB.plugin.js:1175:24)
    at parseCSS (betterdiscord://plugins/0BDFDB.plugin.js:1137:122)
    at requestLibraryData (betterdiscord://plugins/0BDFDB.plugin.js:1180:51)
    at eval (betterdiscord://plugins/0BDFDB.plugin.js:1127:7)
    at args.<computed> (betterdiscord://plugins/0BDFDB.plugin.js:202:20)
    at Function.<anonymous> (betterdiscord/renderer.js:4:327280)
```

**Comment by zerebos** [comment]
> Wow, just got told they won't be downloading the logs and to paste them then just completly ignore you... Rough.

To be clear, I was saying that I wasn't going to download and install _a large number of plugins_ not a log or crash report.
