### ISSUE TITLE
DoNotTrack: Uncaught (in promise) TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by Razzaline** [zerebos/BetterDiscordAddons#737]
Since it runs in the background, I'm not sure if there's another way to check if functionality is broken, but I'm guessing it is based on the console output.

```
DoNotTrack.plugin.js:105 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getCurrentHub')
    at DoNotTrack.onStart (DoNotTrack.plugin.js:105:52)
    at DoNotTrack.start (0PluginLibrary.plugin.js:3663:54)
    at D.startPlugin (renderer.js:5:34310)
    at D.startAddon (renderer.js:5:34103)
    at D.loadAddon (renderer.js:5:6716)
    at D.loadAddon (renderer.js:5:31520)
    at D.loadAllAddons (renderer.js:5:8814)
    at D.initialize (renderer.js:5:3194)
    at D.initialize (renderer.js:5:30719)
    at Object.startup (renderer.js:5:385713)
```

**Comment by zerebos** [comment]
Fixed in the latest version
