### ISSUE TITLE
[Bug] Chat colours stopped working

### ISSUE THREAD

**Issue by glagla00** [zerebos/BetterDiscordAddons#795]
**Which plugin/theme is this about?**

**Describe the Bug**

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

**Comment by WindowsTools2077** [comment]
Plugin name: BetterRoleColors
Plugin version:  0.10.3
Plugin creator: Zerebos
---
Discord version : 1.0.9168.0
---
ZeresPluginLibrary v2.0.22 is enabled
---
I guess it has something to do with PermissionVewer.js, cause that plugin too didn't work today and the BetterRoleColors.js didn't have an addon error msg on Disocrd startup, but the PersmissionVewer.js have it 👇 
![image](https://github.com/user-attachments/assets/56722e07-df14-456a-9c0f-fddf757930b3)

```
TypeError: Cannot read properties of undefined (reading 'Messages')
    at plugin (betterdiscord://plugins/PermissionsViewer.plugin.js:236:84)
    at eval (betterdiscord://plugins/PermissionsViewer.plugin.js:904:13)
    at eval (betterdiscord://plugins/PermissionsViewer.plugin.js:905:3)
    at N.requireAddon (betterdiscord/renderer.js:5:28601)
    at N.loadAddon (betterdiscord/renderer.js:5:6221)
    at N.loadAddon (betterdiscord/renderer.js:5:26269)
    at N.loadAllAddons (betterdiscord/renderer.js:5:9278)
    at N.initialize (betterdiscord/renderer.js:5:3093)
    at N.initialize (betterdiscord/renderer.js:5:25382)
    at Object.startup (betterdiscord/renderer.js:5:408589)
```

Plugin name:  PermissionsViewer
Plugin version: 0.2.11
Plugin creator: Zerebos

I hope that was useful ❇️

**Comment by NeoZar** [comment]
Перестал работать

**Comment by B-Nerd** [comment]
i have ZeresPluginLibrary working with no error but still the colors are not showing

**Comment by BladeofRagna** [comment]
Same here as well.
Seems like from one of the discord updates recently that broke BD, certain plugins like this one got borked as well and not entirely sure if there's a self-fix that can be done in the meantime

**Comment by zerebos** [comment]
Sorry but BetterRoleColors has been discontinued. I recommend using [MoreRoleColors](https://betterdiscord.app/plugin/MoreRoleColors).
